# ==========================================
# Application
# ==========================================
spring.application.name=job-tracker

# ==========================================
# Logging - Production
# ==========================================
logging.level.root=INFO
logging.level.com.job_tracker=INFO

# Spring
logging.level.org.springframework=WARN
logging.level.org.springframework.web=WARN

# Hibernate / JPA
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN

# ==========================================
# Log File
# ==========================================
logging.file.name=logs/job-tracker.log

# ==========================================
# Log Format
# ==========================================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n